spring:
    datasource:
        url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
        username: postgres.hvsnudhbjrrcggvekucm
        password: supabase9911
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 2
            minimum-idle: 1
            connection-timeout: 60000
            idle-timeout: 300000
            max-lifetime: 600000
    jpa:
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
        properties:
            hibernate:
                dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
        open-in-view: false

server:
    port: ${PORT:8080}